apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
      default: main
    - name: image-name
      type: string
    - name: build-destination
      type: string
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
    - name: lint
      taskRef:
        name: flake8
        kind: Task
      params:
        - name: repo-url
          value: $(params.repo-url)
      runAfter:
        - clone
    - name: tests
      taskRef:
        name: pytest
        kind: Task
      params:
        - name: repo-url
          value: $(params.repo-url)
      runAfter:
        - lint
    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: IMAGE
          value: $(params.build-destination)
      runAfter:
        - tests
    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc rollout restart deployment/$(params.image-name)
      runAfter:
        - build
